title: Book Notes
author: Michael T. Moen
copyright: "2024"
logo: jonah_window.jpg
exclude_patterns: [old, conversion_scripts]
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/MoenMi/book-notes  # Online location of your book
#  path_to_book: # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    redirrafe_branch: 'master'
    redirrafe_redirects:
      books/odyssey/intro.md: books/odyssey/introduction.md

extra_extensions:
  - sphinxext.rediraffe

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: jonah_window.jpg
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  colab_url: ""
  binderhub_url: ""
  jupyterhub_url: ""
